name: koperasi_ksmi
description: "Aplikasi Koperasi KSMI"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.0.0
  image_picker: ^1.1.0
  http: ^1.1.0
  image: ^4.0.17
  timezone: ^0.9.4
  firebase_core: ^2.32.0  # ✅ JANGAN UPDATE - PAKAI INI
  firebase_messaging: ^14.7.10  # ✅ JANGAN UPDATE - PAKAI INI
  flutter_local_notifications: ^16.3.3  # ✅ JANGAN UPDATE - PAKAI INI
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.0.0
  path_provider: ^2.1.5
  workmanager: ^0.0.0  # ✅ TURUNKAN KE 0.5.1 ATAU HAPUS SAJA

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/KSMI_LOGO.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/KSMI_LOGO.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/KSMI_LOGO.png